<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net8.0-windows;net472</TargetFrameworks>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DevExpress.Wpf.Core" Version="24.2.*-*" />
    <PackageReference Include="DevExpress.Wpf.PropertyGrid" Version="24.2.*-*" />
    <PackageReference Include="DevExpress.Wpf.Themes.All" Version="24.2.*-*" />
  </ItemGroup>

</Project>
