<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OptionInfer>On</OptionInfer>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net8.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <ApplicationDefinition Include="App.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.Wpf.Core" Version="24.2.*-*" />
    <PackageReference Include="DevExpress.Wpf.PropertyGrid" Version="24.2.*-*" />
    <PackageReference Include="DevExpress.Wpf.Themes.All" Version="24.2.*-*" />
  </ItemGroup>
</Project>